/**
 * Application constants including roles, permissions, and status values
 */

// User Roles
const ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  TECHNICIAN: 'TECHNICIAN'
};

// Maintenance Types
const MAINTENANCE_TYPES = {
  CORRECTIVE: 'CORRECTIVE',
  PREVENTIVE: 'PREVENTIVE'
};

// Maintenance Status
const MAINTENANCE_STATUS = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  REPAIRED: 'REPAIRED',
  SCRAP: 'SCRAP'
};

// Permission Groups
const PERMISSIONS = {
  // User Management
  MANAGE_USERS: [ROLES.ADMIN],
  VIEW_ALL_USERS: [ROLES.ADMIN],
  VIEW_TEAM_USERS: [ROLES.ADMIN, ROLES.MANAGER],
  
  // Team Management
  MANAGE_TEAMS: [ROLES.ADMIN],
  VIEW_TEAMS: [ROLES.ADMIN, ROLES.MANAGER],
  
  // Equipment Management
  MANAGE_EQUIPMENT: [ROLES.ADMIN, ROLES.MANAGER],
  VIEW_EQUIPMENT: [ROLES.ADMIN, ROLES.MANAGER, ROLES.TECHNICIAN],
  SCRAP_EQUIPMENT: [ROLES.ADMIN, ROLES.MANAGER],
  
  // Maintenance Request Management
  CREATE_REQUESTS: [ROLES.ADMIN, ROLES.MANAGER],
  ASSIGN_REQUESTS: [ROLES.ADMIN, ROLES.MANAGER],
  VIEW_ALL_REQUESTS: [ROLES.ADMIN],
  VIEW_TEAM_REQUESTS: [ROLES.ADMIN, ROLES.MANAGER],
  VIEW_ASSIGNED_REQUESTS: [ROLES.TECHNICIAN],
  UPDATE_REQUEST_STATUS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.TECHNICIAN],
  COMPLETE_REQUESTS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.TECHNICIAN],
  SCRAP_REQUESTS: [ROLES.ADMIN, ROLES.MANAGER],
  
  // Dashboard and Reporting
  VIEW_DASHBOARD: [ROLES.ADMIN, ROLES.MANAGER],
  VIEW_REPORTS: [ROLES.ADMIN, ROLES.MANAGER],
  VIEW_STATISTICS: [ROLES.ADMIN, ROLES.MANAGER],
  
  // Audit Logs
  VIEW_AUDIT_LOGS: [ROLES.ADMIN, ROLES.MANAGER],
  
  // System Administration
  SYSTEM_ADMIN: [ROLES.ADMIN]
};

// HTTP Status Codes
const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500
};

// Error Codes
const ERROR_CODES = {
  // Authentication Errors
  MISSING_TOKEN: 'MISSING_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  
  // Authorization Errors
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  TEAM_ACCESS_DENIED: 'TEAM_ACCESS_DENIED',
  RESOURCE_ACCESS_DENIED: 'RESOURCE_ACCESS_DENIED',
  
  // Validation Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_INPUT: 'INVALID_INPUT',
  
  // Business Logic Errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  EQUIPMENT_NOT_FOUND: 'EQUIPMENT_NOT_FOUND',
  REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
  EQUIPMENT_SCRAPPED: 'EQUIPMENT_SCRAPPED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  TEAM_ASSIGNMENT_MISMATCH: 'TEAM_ASSIGNMENT_MISMATCH',
  
  // System Errors
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
};

// Success Messages
const SUCCESS_MESSAGES = {
  USER_CREATED: 'User created successfully',
  USER_UPDATED: 'User updated successfully',
  USER_DELETED: 'User deleted successfully',
  TEAM_CREATED: 'Team created successfully',
  TEAM_UPDATED: 'Team updated successfully',
  EQUIPMENT_CREATED: 'Equipment created successfully',
  EQUIPMENT_UPDATED: 'Equipment updated successfully',
  EQUIPMENT_SCRAPPED: 'Equipment marked as scrapped',
  REQUEST_CREATED: 'Maintenance request created successfully',
  REQUEST_UPDATED: 'Maintenance request updated successfully',
  REQUEST_ASSIGNED: 'Maintenance request assigned successfully',
  REQUEST_COMPLETED: 'Maintenance request completed successfully',
  REQUEST_SCRAPPED: 'Maintenance request marked as scrap',
  LOGIN_SUCCESS: 'Login successful',
  LOGOUT_SUCCESS: 'Logout successful'
};

// Validation Rules
const VALIDATION_RULES = {
  PASSWORD_MIN_LENGTH: 8,
  NAME_MIN_LENGTH: 2,
  NAME_MAX_LENGTH: 100,
  EMAIL_MAX_LENGTH: 255,
  SUBJECT_MAX_LENGTH: 200,
  DESCRIPTION_MAX_LENGTH: 1000,
  SERIAL_NUMBER_MAX_LENGTH: 100,
  DEPARTMENT_MAX_LENGTH: 100,
  LOCATION_MAX_LENGTH: 200
};

// Default Values
const DEFAULTS = {
  JWT_EXPIRES_IN: '24h',
  JWT_REFRESH_EXPIRES_IN: '7d',
  BCRYPT_SALT_ROUNDS: 12,
  PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100
};

module.exports = {
  ROLES,
  MAINTENANCE_TYPES,
  MAINTENANCE_STATUS,
  PERMISSIONS,
  HTTP_STATUS,
  ERROR_CODES,
  SUCCESS_MESSAGES,
  VALIDATION_RULES,
  DEFAULTS
};